[package]
name = "sankode-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "AOT Native Compiler and C Code Generator for Sankode"

[dependencies]
sankode-core = { path = "../sankode-core" }
thiserror.workspace = true
colored.workspace = true

[dev-dependencies]
sankode-lexer = { path = "../sankode-lexer" }
sankode-parser = { path = "../sankode-parser" }
