use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::process::Command;
use sankode_core::ast::*;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CodegenError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Compilation error: {0}")]
    Compile(String),
    #[error("Codegen error: {0}")]
    General(String),
}

pub fn mangle_ident(s: &str) -> String {
    let mut out = String::from("_snk_");
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push_str(&format!("x{:04x}", ch as u32));
        }
    }
    out
}

pub struct CodeGenerator {
    current_struct: Option<String>,
    struct_defs: HashMap<String, StructDecl>,
}

impl CodeGenerator {
    pub fn new() -> Self {
        CodeGenerator {
            current_struct: None,
            struct_defs: HashMap::new(),
        }
    }

    pub fn generate_c(&mut self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str("/* Generated by Sankode AOT Compiler */\n");
        out.push_str(C_RUNTIME);
        out.push_str("\n\n");

        let mut functions: Vec<FunctionDecl> = Vec::new();
        let mut top_stmts: Vec<Statement> = Vec::new();
        let mut impl_methods: HashMap<String, Vec<FunctionDecl>> = HashMap::new();

        for item in &program.items {
            match item {
                TopLevelItem::Struct(st) => {
                    self.struct_defs.insert(st.name.clone(), st.clone());
                }
                TopLevelItem::Function(func) => {
                    functions.push(func.clone());
                }
                TopLevelItem::Impl(imp) => {
                    impl_methods.entry(imp.target.clone()).or_default().extend(imp.methods.clone());
                }
                TopLevelItem::Statement(stmt) => {
                    top_stmts.push(stmt.clone());
                }
                TopLevelItem::Comment(_) => {}
            }
        }

        // 1. Enum for Struct Type Tags
        out.push_str("/* === Struct Type Tags === */\n");
        out.push_str("enum {\n    TAG_NONE = 0,\n");
        let mut tag_counter = 1;
        for (name, _) in &self.struct_defs {
            out.push_str(&format!("    TAG_{} = {},\n", mangle_ident(name), tag_counter));
            tag_counter += 1;
        }
        out.push_str("};\n\n");

        // 2. Forward Declarations for Structs
        out.push_str("/* === Forward Struct Declarations === */\n");
        for (name, _) in &self.struct_defs {
            out.push_str(&format!("typedef struct {} {};\n", mangle_ident(name), mangle_ident(name)));
        }
        out.push_str("\n");

        // 3. Struct Type Definitions
        out.push_str("/* === Struct Definitions === */\n");
        for (name, st) in &self.struct_defs {
            let sm = mangle_ident(name);
            out.push_str(&format!("struct {} {{\n", sm));
            for f in &st.fields {
                out.push_str(&format!("    SnkValue {};\n", mangle_ident(&f.name)));
            }
            out.push_str("};\n\n");
        }

        // 4. Struct Constructors
        out.push_str("/* === Struct Constructors === */\n");
        for (name, st) in &self.struct_defs {
            let sm = mangle_ident(name);
            let params: Vec<String> = st.fields.iter().map(|f| format!("SnkValue {}", mangle_ident(&f.name))).collect();
            out.push_str(&format!("static inline SnkValue snk_create_{}({}) {{\n", sm, params.join(", ")));
            out.push_str(&format!("    {}* _s = ({}*)malloc(sizeof({}));\n", sm, sm, sm));
            for f in &st.fields {
                let fm = mangle_ident(&f.name);
                out.push_str(&format!("    _s->{} = {};\n", fm, fm));
            }
            out.push_str(&format!("    return snk_val_ptr((void*)_s, TAG_{});\n", sm));
            out.push_str("}\n\n");
        }

        // 5. Forward Declarations of Methods & Functions
        out.push_str("/* === Function Declarations === */\n");
        for func in &functions {
            let fn_name = if func.name == "मुख्य" {
                "snk_main_entry".to_string()
            } else {
                mangle_ident(&func.name)
            };
            let params: Vec<String> = func.params.iter().map(|p| format!("SnkValue {}", mangle_ident(&p.name))).collect();
            out.push_str(&format!("SnkValue {}({});\n", fn_name, params.join(", ")));
        }

        for (st_name, methods) in &impl_methods {
            let struct_m = mangle_ident(st_name);
            for m in methods {
                let method_m = format!("{}_{}", struct_m, mangle_ident(&m.name));
                let mut params = Vec::new();
                for p in &m.params {
                    if p.name == "स्व" {
                        params.push(format!("{}* _self", struct_m));
                    } else {
                        params.push(format!("SnkValue {}", mangle_ident(&p.name)));
                    }
                }
                out.push_str(&format!("SnkValue {}({});\n", method_m, params.join(", ")));
            }
        }
        out.push_str("\n");

        // 6. Field Access Dispatchers
        out.push_str("/* === Field Access Dispatchers === */\n");
        let mut field_to_structs: HashMap<String, Vec<String>> = HashMap::new();
        for (st_name, st) in &self.struct_defs {
            for f in &st.fields {
                field_to_structs.entry(f.name.clone()).or_default().push(st_name.clone());
            }
        }
        for (fname, st_list) in &field_to_structs {
            let fm = mangle_ident(fname);
            out.push_str(&format!("static inline SnkValue snk_field_{}(SnkValue target) {{\n", fm));
            out.push_str("    if (!target.as.ptr) return snk_val_unit();\n");
            out.push_str("    switch (target.type_tag) {\n");
            for st_name in st_list {
                let sm = mangle_ident(st_name);
                out.push_str(&format!("        case TAG_{}: return (({}*)target.as.ptr)->{};\n", sm, sm, fm));
            }
            out.push_str("        default: return snk_val_unit();\n");
            out.push_str("    }\n");
            out.push_str("}\n\n");
        }

        // 7. Method Call Dispatchers
        out.push_str("/* === Method Call Dispatchers === */\n");
        let mut method_to_structs: HashMap<String, Vec<(String, usize)>> = HashMap::new();
        for (st_name, methods) in &impl_methods {
            for m in methods {
                let param_count = m.params.iter().filter(|p| p.name != "स्व").count();
                method_to_structs.entry(m.name.clone()).or_default().push((st_name.clone(), param_count));
            }
        }
        for (mname, st_list) in &method_to_structs {
            let mm = mangle_ident(mname);
            let param_count = st_list[0].1;
            let mut param_decls = Vec::new();
            let mut param_names = Vec::new();
            for i in 0..param_count {
                param_decls.push(format!("SnkValue a{}", i));
                param_names.push(format!("a{}", i));
            }
            let all_params = if param_decls.is_empty() {
                "SnkValue target".to_string()
            } else {
                format!("SnkValue target, {}", param_decls.join(", "))
            };

            out.push_str(&format!("static inline SnkValue snk_call_{}({}) {{\n", mm, all_params));
            out.push_str("    if (!target.as.ptr) return snk_val_unit();\n");
            out.push_str("    switch (target.type_tag) {\n");
            for (st_name, _) in st_list {
                let sm = mangle_ident(st_name);
                let call_args = if param_names.is_empty() {
                    format!("({}*)target.as.ptr", sm)
                } else {
                    format!("({}*)target.as.ptr, {}", sm, param_names.join(", "))
                };
                out.push_str(&format!("        case TAG_{}: return {}_{}({});\n", sm, sm, mm, call_args));
            }
            out.push_str("        default: return snk_val_unit();\n");
            out.push_str("    }\n");
            out.push_str("}\n\n");
        }

        // 8. Implementations of Functions & Methods
        out.push_str("/* === Function Implementations === */\n");
        let mut has_main = false;
        for func in &functions {
            if func.name == "मुख्य" {
                has_main = true;
            }
            out.push_str(&self.gen_function(func, None)?);
            out.push_str("\n");
        }

        for (st_name, methods) in &impl_methods {
            for m in methods {
                out.push_str(&self.gen_function(m, Some(st_name))?);
                out.push_str("\n");
            }
        }

        // If top-level statements exist or no main function:
        if !top_stmts.is_empty() || !has_main {
            out.push_str("SnkValue snk_toplevel_run() {\n");
            for st in &top_stmts {
                out.push_str(&self.gen_stmt(st, 1)?);
            }
            if has_main {
                out.push_str("    return snk_main_entry();\n");
            } else {
                out.push_str("    return snk_val_unit();\n");
            }
            out.push_str("}\n\n");
        }

        // C main() entrypoint
        let main_call = if !top_stmts.is_empty() || !has_main {
            "snk_toplevel_run();"
        } else {
            "snk_main_entry();"
        };

        out.push_str(&format!(r#"
int main(int argc, char** argv) {{
    (void)argc; (void)argv;
#ifdef _WIN32
    SetConsoleOutputCP(CP_UTF8);
#endif
    {}
    return 0;
}}
"#, main_call));

        Ok(out)
    }

    fn gen_function(&mut self, func: &FunctionDecl, parent_struct: Option<&str>) -> Result<String, CodegenError> {
        let prev_struct = self.current_struct.clone();
        self.current_struct = parent_struct.map(|s| s.to_string());

        let fn_name = if let Some(st) = parent_struct {
            format!("{}_{}", mangle_ident(st), mangle_ident(&func.name))
        } else if func.name == "मुख्य" {
            "snk_main_entry".to_string()
        } else {
            mangle_ident(&func.name)
        };

        let mut params = Vec::new();
        for p in &func.params {
            if p.name == "स्व" {
                let st_name = parent_struct.unwrap_or("void");
                params.push(format!("{}* _self", mangle_ident(st_name)));
            } else {
                params.push(format!("SnkValue {}", mangle_ident(&p.name)));
            }
        }

        let mut s = format!("SnkValue {}({}) {{\n", fn_name, params.join(", "));
        for stmt in &func.body {
            s.push_str(&self.gen_stmt(stmt, 1)?);
        }
        s.push_str("    return snk_val_unit();\n");
        s.push_str("}\n");

        self.current_struct = prev_struct;
        Ok(s)
    }

    fn gen_stmt(&mut self, stmt: &Statement, indent: usize) -> Result<String, CodegenError> {
        let pad = "    ".repeat(indent);
        let mut s = String::new();
        match stmt {
            Statement::VarDecl { name, init, .. } => {
                let mangled = mangle_ident(name);
                let init_c = self.gen_expr(init)?;
                s.push_str(&format!("{}SnkValue {} = {};\n", pad, mangled, init_c));
            }
            Statement::Assignment { target, value, .. } => {
                let mangled = mangle_ident(target);
                let val_c = self.gen_expr(value)?;
                s.push_str(&format!("{}{} = {};\n", pad, mangled, val_c));
            }
            Statement::FieldAssignment { target, field, value, .. } => {
                let val_c = self.gen_expr(value)?;
                let field_m = mangle_ident(field);
                if target == "स्व" {
                    s.push_str(&format!("{}_self->{} = {};\n", pad, field_m, val_c));
                } else {
                    let target_m = mangle_ident(target);
                    s.push_str(&format!("{}((struct _snk_struct_raw*){}.as.ptr)->fields[{}] = {};\n", pad, target_m, 0, val_c));
                }
            }
            Statement::IndexAssignment { target, index, value, .. } => {
                let target_c = self.gen_expr(target)?;
                let idx_c = self.gen_expr(index)?;
                let val_c = self.gen_expr(value)?;
                s.push_str(&format!("{}snk_list_set({}, {}, {});\n", pad, target_c, idx_c, val_c));
            }
            Statement::If { condition, then_branch, else_branch, .. } => {
                let cond_c = self.gen_expr(condition)?;
                s.push_str(&format!("{}if (snk_to_bool({})) {{\n", pad, cond_c));
                for st in then_branch {
                    s.push_str(&self.gen_stmt(st, indent + 1)?);
                }
                if let Some(eb) = else_branch {
                    s.push_str(&format!("{}}} else {{\n", pad));
                    for st in eb {
                        s.push_str(&self.gen_stmt(st, indent + 1)?);
                    }
                }
                s.push_str(&format!("{}}}\n", pad));
            }
            Statement::While { condition, body, .. } => {
                let cond_c = self.gen_expr(condition)?;
                s.push_str(&format!("{}while (snk_to_bool({})) {{\n", pad, cond_c));
                for st in body {
                    s.push_str(&self.gen_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{}}}\n", pad));
            }
            Statement::Return { value, .. } => {
                if let Some(e) = value {
                    let val_c = self.gen_expr(e)?;
                    s.push_str(&format!("{}return {};\n", pad, val_c));
                } else {
                    s.push_str(&format!("{}return snk_val_unit();\n", pad));
                }
            }
            Statement::Expr(expr) => {
                let expr_c = self.gen_expr(expr)?;
                s.push_str(&format!("{}{};\n", pad, expr_c));
            }
        }
        Ok(s)
    }

    fn gen_expr(&mut self, expr: &Expr) -> Result<String, CodegenError> {
        match &expr.kind {
            ExprKind::DevanagariInteger(i, _) => Ok(format!("snk_val_int({}LL)", i)),
            ExprKind::DevanagariFloat(f, _) => Ok(format!("snk_val_float({:.10})", f)),
            ExprKind::StringLiteral(s) => {
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r").replace('\t', "\\t");
                Ok(format!("snk_val_str(\"{}\")", escaped))
            }
            ExprKind::BoolLiteral(b) => Ok(format!("snk_val_bool({})", if *b { "true" } else { "false" })),
            ExprKind::Identifier(id) => {
                if id == "स्व" {
                    Ok("_self".to_string())
                } else {
                    Ok(mangle_ident(id))
                }
            }
            ExprKind::Binary { left, op, right } => {
                let l_c = self.gen_expr(left)?;
                let r_c = self.gen_expr(right)?;
                let fn_call = match op {
                    BinaryOp::Add => format!("snk_add({}, {})", l_c, r_c),
                    BinaryOp::Sub => format!("snk_sub({}, {})", l_c, r_c),
                    BinaryOp::Mul => format!("snk_mul({}, {})", l_c, r_c),
                    BinaryOp::Div => format!("snk_div({}, {})", l_c, r_c),
                    BinaryOp::Mod => format!("snk_mod({}, {})", l_c, r_c),
                    BinaryOp::Equal => format!("snk_eq({}, {})", l_c, r_c),
                    BinaryOp::NotEqual => format!("snk_ne({}, {})", l_c, r_c),
                    BinaryOp::Less => format!("snk_lt({}, {})", l_c, r_c),
                    BinaryOp::Greater => format!("snk_gt({}, {})", l_c, r_c),
                    BinaryOp::LessEq => format!("snk_le({}, {})", l_c, r_c),
                    BinaryOp::GreaterEq => format!("snk_ge({}, {})", l_c, r_c),
                };
                Ok(fn_call)
            }
            ExprKind::Unary { op, expr: inner } => {
                let inner_c = self.gen_expr(inner)?;
                match op {
                    UnaryOp::Not => Ok(format!("snk_not({})", inner_c)),
                    UnaryOp::Neg => Ok(format!("snk_neg({})", inner_c)),
                }
            }
            ExprKind::Call { callee, args } => {
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.gen_expr(a)?);
                }

                match callee.as_str() {
                    "मुद्रय" | "मुद्रण" => Ok(format!("snk_print({}, {})", arg_strs.len(), arg_strs.join(", "))),
                    "दशमलव" | "अंशाङ्क" => Ok(format!("snk_to_float({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "पूर्णाङ्क" => Ok(format!("snk_val_int(snk_to_i64({}))", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "घाताङ्क" => Ok(format!("snk_exp({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "वर्गमूल" => Ok(format!("snk_sqrt({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "लॉग" => Ok(format!("snk_log({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "रेलू" => Ok(format!("snk_relu({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "महत्तम" => Ok(format!("snk_max({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "न्यूनतम" => Ok(format!("snk_min({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "आकार" | "सूची_दैर्घ्यम्" => Ok(format!("snk_size({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "सूची_सृज" => {
                        let len_arg = arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_int(0)".to_string());
                        let def_arg = arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string());
                        Ok(format!("snk_list_create({}, {})", len_arg, def_arg))
                    }
                    "योजय" | "सूची_संयोजय" => Ok(format!("snk_list_append({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "विभाजय" | "सूत्र_विभाजय" => Ok(format!("snk_str_split({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "संयोजय" | "सूची_संयोग" => Ok(format!("snk_list_join({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "खण्ड" | "सूत्र_अंश" => Ok(format!("snk_str_slice({}, {}, {})",
                        arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()),
                        arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()),
                        arg_strs.get(2).cloned().unwrap_or_else(|| "snk_val_unit()".to_string())
                    )),
                    "अक्षरम्" | "सूत्र_वर्ण" => Ok(format!("snk_str_char_at({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "दैर्घ्यम्" | "सूत्र_दैर्घ्यम्" => Ok(format!("snk_str_len({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "संख्या" | "संख्या_पाठ" => Ok(format!("snk_str_to_num({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "सूत्रम्" | "सूत्र_रूप" => Ok(format!("snk_to_str({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "संचिका_पठ" => Ok(format!("snk_file_read({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "संचिका_लिख" | "संचिका_लेख" => Ok(format!("snk_file_write({}, {})", arg_strs.get(0).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()), arg_strs.get(1).cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    "संचिका_अस्ति" | "संचिका_विद्यते" => Ok(format!("snk_file_exists({})", arg_strs.first().cloned().unwrap_or_else(|| "snk_val_unit()".to_string()))),
                    _ => {
                        let fn_m = mangle_ident(callee);
                        Ok(format!("{}({})", fn_m, arg_strs.join(", ")))
                    }
                }
            }
            ExprKind::MethodCall { target, method, args } => {
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.gen_expr(a)?);
                }

                if let ExprKind::Identifier(id) = &target.kind {
                    if id == "स्व" {
                        if let Some(cur_st) = &self.current_struct {
                            let struct_m = mangle_ident(cur_st);
                            let method_m = format!("{}_{}", struct_m, mangle_ident(method));
                            let all_args = if arg_strs.is_empty() {
                                "_self".to_string()
                            } else {
                                format!("_self, {}", arg_strs.join(", "))
                            };
                            return Ok(format!("{}({})", method_m, all_args));
                        }
                    }
                }

                let target_c = self.gen_expr(target)?;
                let method_m = mangle_ident(method);
                let all_args = if arg_strs.is_empty() {
                    target_c
                } else {
                    format!("{}, {}", target_c, arg_strs.join(", "))
                };
                Ok(format!("snk_call_{}({})", method_m, all_args))
            }
            ExprKind::FieldAccess { target, field } => {
                let field_m = mangle_ident(field);
                if let ExprKind::Identifier(id) = &target.kind {
                    if id == "स्व" {
                        return Ok(format!("_self->{}", field_m));
                    }
                }
                let target_c = self.gen_expr(target)?;
                Ok(format!("snk_field_{}({})", field_m, target_c))
            }
            ExprKind::StructInit { name, fields } => {
                let struct_m = mangle_ident(name);
                let mut field_map: HashMap<&str, &Expr> = HashMap::new();
                for (fname, fval) in fields {
                    field_map.insert(fname.as_str(), fval);
                }
                let mut ordered_vals = Vec::new();
                let decl_field_names: Option<Vec<String>> = self.struct_defs.get(name).map(|st| st.fields.iter().map(|f| f.name.clone()).collect());
                if let Some(field_names) = decl_field_names {
                    for decl_f in &field_names {
                        if let Some(fval) = field_map.get(decl_f.as_str()) {
                            ordered_vals.push(self.gen_expr(fval)?);
                        } else {
                            ordered_vals.push("snk_val_unit()".to_string());
                        }
                    }
                } else {
                    for (_, fval) in fields {
                        ordered_vals.push(self.gen_expr(fval)?);
                    }
                }
                Ok(format!("snk_create_{}({})", struct_m, ordered_vals.join(", ")))
            }
            ExprKind::Borrow { expr: inner, .. } => {
                self.gen_expr(inner)
            }
            ExprKind::ArrayLiteral(elements) => {
                let mut items = Vec::new();
                for e in elements {
                    items.push(self.gen_expr(e)?);
                }
                let mut s = format!("snk_list_create(snk_val_int({}), snk_val_unit())", items.len());
                for it in items {
                    s = format!("snk_list_append({}, {})", s, it);
                }
                Ok(s)
            }
            ExprKind::Index { target, index } => {
                let target_c = self.gen_expr(target)?;
                let idx_c = self.gen_expr(index)?;
                Ok(format!("snk_list_get({}, {})", target_c, idx_c))
            }
        }
    }
}

pub fn compile_to_binary(c_code: &str, output_exe: &Path, emit_c: Option<&Path>) -> Result<(), CodegenError> {
    let temp_c = if let Some(p) = emit_c {
        p.to_path_buf()
    } else {
        std::env::temp_dir().join(format!("sankode_tmp_{}.c", std::process::id()))
    };

    fs::write(&temp_c, c_code)?;

    let clean_c = || {
        if emit_c.is_none() {
            let _ = fs::remove_file(&temp_c);
        }
    };

    // Try MSVC cl.exe first on Windows
    #[cfg(target_os = "windows")]
    {
        // Try cl in PATH
        let cl_res = Command::new("cl")
            .arg("/nologo")
            .arg("/utf-8")
            .arg("/O2")
            .arg(&temp_c)
            .arg(format!("/Fe:{}", output_exe.display()))
            .output();

        if let Ok(out) = cl_res {
            if out.status.success() {
                let obj_path = output_exe.with_extension("obj");
                let _ = fs::remove_file(obj_path);
                clean_c();
                return Ok(());
            }
        }

        // Try standard MSVC vcvars64.bat paths
        let vcvars_candidates = [
            r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat",
        ];

        for vcvars in vcvars_candidates {
            if Path::new(vcvars).exists() {
                let temp_bat = std::env::temp_dir().join(format!("sankode_msvc_{}.bat", std::process::id()));
                let out_str = output_exe.to_string_lossy().replace('/', "\\");
                let src_str = temp_c.to_string_lossy().replace('/', "\\");
                let bat_content = format!(
                    "@echo off\r\ncall \"{}\" >nul 2>&1\r\ncl /nologo /utf-8 /O2 /Fe:\"{}\" \"{}\"\r\nif %errorlevel% neq 0 exit /b %errorlevel%\r\n",
                    vcvars,
                    out_str,
                    src_str
                );
                fs::write(&temp_bat, bat_content)?;
                let bat_str = temp_bat.to_string_lossy().replace('/', "\\");
                let out = Command::new("cmd").args(["/c", &bat_str]).output()?;
                let _ = fs::remove_file(&temp_bat);
                if out.status.success() {
                    let obj_path = output_exe.with_extension("obj");
                    let _ = fs::remove_file(obj_path);
                    clean_c();
                    return Ok(());
                }
            }
        }
    }

    // Try GCC or Clang
    let gcc_res = Command::new("gcc")
        .arg("-O2")
        .arg("-std=c99")
        .arg(&temp_c)
        .arg("-lm")
        .arg("-o")
        .arg(output_exe)
        .output();

    if let Ok(out) = gcc_res {
        if out.status.success() {
            clean_c();
            return Ok(());
        }
    }

    let clang_res = Command::new("clang")
        .arg("-O2")
        .arg("-std=c99")
        .arg(&temp_c)
        .arg("-lm")
        .arg("-o")
        .arg(output_exe)
        .output();

    if let Ok(out) = clang_res {
        if out.status.success() {
            clean_c();
            return Ok(());
        }
    }

    clean_c();
    Err(CodegenError::Compile("No suitable C compiler (MSVC cl.exe, GCC, or Clang) found or compilation failed.".to_string()))
}

pub fn generate_c_source(program: &Program) -> Result<String, CodegenError> {
    let mut cg = CodeGenerator::new();
    cg.generate_c(program)
}

pub fn compile_program_to_binary(program: &Program, output_exe: &Path) -> Result<(), CodegenError> {
    let c_code = generate_c_source(program)?;
    compile_to_binary(&c_code, output_exe, None)
}

pub const C_RUNTIME: &str = r#"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include <stdarg.h>

#ifdef _WIN32
#include <windows.h>
#endif

typedef enum {
    SNK_UNIT = 0,
    SNK_INT,
    SNK_FLOAT,
    SNK_BOOL,
    SNK_STR,
    SNK_LIST,
    SNK_PTR
} SnkType;

typedef struct SnkValue SnkValue;
typedef struct SnkList SnkList;

struct SnkList {
    SnkValue* items;
    int64_t len;
    int64_t cap;
};

struct SnkValue {
    SnkType type;
    int32_t type_tag;
    union {
        int64_t i;
        double f;
        bool b;
        char* s;
        SnkList* list;
        void* ptr;
    } as;
};

static inline SnkValue snk_val_unit() { SnkValue v; v.type = SNK_UNIT; v.type_tag = 0; v.as.i = 0; return v; }
static inline SnkValue snk_val_int(int64_t i) { SnkValue v; v.type = SNK_INT; v.type_tag = 0; v.as.i = i; return v; }
static inline SnkValue snk_val_float(double f) { SnkValue v; v.type = SNK_FLOAT; v.type_tag = 0; v.as.f = f; return v; }
static inline SnkValue snk_val_bool(bool b) { SnkValue v; v.type = SNK_BOOL; v.type_tag = 0; v.as.b = b; return v; }
static inline SnkValue snk_val_str(const char* s) {
    SnkValue v; v.type = SNK_STR; v.type_tag = 0;
    if (s) {
        size_t len = strlen(s);
        v.as.s = (char*)malloc(len + 1);
        memcpy(v.as.s, s, len + 1);
    } else {
        v.as.s = (char*)calloc(1, 1);
    }
    return v;
}
static inline SnkValue snk_val_list(SnkList* l) { SnkValue v; v.type = SNK_LIST; v.type_tag = 0; v.as.list = l; return v; }
static inline SnkValue snk_val_ptr(void* p, int32_t tag) { SnkValue v; v.type = SNK_PTR; v.type_tag = tag; v.as.ptr = p; return v; }

static inline bool snk_to_bool(SnkValue v) {
    if (v.type == SNK_BOOL) return v.as.b;
    if (v.type == SNK_INT) return v.as.i != 0;
    if (v.type == SNK_FLOAT) return v.as.f != 0.0;
    if (v.type == SNK_STR) return v.as.s && v.as.s[0] != '\0';
    if (v.type == SNK_LIST) return v.as.list && v.as.list->len > 0;
    if (v.type == SNK_PTR) return v.as.ptr != NULL;
    return false;
}

static inline double snk_to_f64(SnkValue v) {
    if (v.type == SNK_FLOAT) return v.as.f;
    if (v.type == SNK_INT) return (double)v.as.i;
    if (v.type == SNK_BOOL) return v.as.b ? 1.0 : 0.0;
    return 0.0;
}

static inline int64_t snk_to_i64(SnkValue v) {
    if (v.type == SNK_INT) return v.as.i;
    if (v.type == SNK_FLOAT) return (int64_t)v.as.f;
    if (v.type == SNK_BOOL) return v.as.b ? 1 : 0;
    return 0;
}

static inline SnkValue snk_to_float(SnkValue v) {
    return snk_val_float(snk_to_f64(v));
}

/* Math intrinsics */
static inline SnkValue snk_sqrt(SnkValue v) { return snk_val_float(sqrt(snk_to_f64(v))); }
static inline SnkValue snk_exp(SnkValue v) { return snk_val_float(exp(snk_to_f64(v))); }
static inline SnkValue snk_log(SnkValue v) { return snk_val_float(log(snk_to_f64(v))); }
static inline SnkValue snk_relu(SnkValue v) {
    if (v.type == SNK_FLOAT) return snk_val_float(v.as.f > 0.0 ? v.as.f : 0.0);
    return snk_val_int(v.as.i > 0 ? v.as.i : 0);
}
static inline SnkValue snk_max(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) {
        double fa = snk_to_f64(a); double fb = snk_to_f64(b);
        return snk_val_float(fa > fb ? fa : fb);
    }
    int64_t ia = snk_to_i64(a); int64_t ib = snk_to_i64(b);
    return snk_val_int(ia > ib ? ia : ib);
}
static inline SnkValue snk_min(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) {
        double fa = snk_to_f64(a); double fb = snk_to_f64(b);
        return snk_val_float(fa < fb ? fa : fb);
    }
    int64_t ia = snk_to_i64(a); int64_t ib = snk_to_i64(b);
    return snk_val_int(ia < ib ? ia : ib);
}

/* Arithmetic Operations */
static inline SnkValue snk_add(SnkValue a, SnkValue b) {
    if (a.type == SNK_STR && b.type == SNK_STR) {
        size_t la = strlen(a.as.s); size_t lb = strlen(b.as.s);
        char* ns = (char*)malloc(la + lb + 1);
        memcpy(ns, a.as.s, la);
        memcpy(ns + la, b.as.s, lb + 1);
        SnkValue v; v.type = SNK_STR; v.type_tag = 0; v.as.s = ns;
        return v;
    }
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) {
        return snk_val_float(snk_to_f64(a) + snk_to_f64(b));
    }
    return snk_val_int(snk_to_i64(a) + snk_to_i64(b));
}

static inline SnkValue snk_sub(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) {
        return snk_val_float(snk_to_f64(a) - snk_to_f64(b));
    }
    return snk_val_int(snk_to_i64(a) - snk_to_i64(b));
}

static inline SnkValue snk_mul(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) {
        return snk_val_float(snk_to_f64(a) * snk_to_f64(b));
    }
    return snk_val_int(snk_to_i64(a) * snk_to_i64(b));
}

static inline SnkValue snk_div(SnkValue a, SnkValue b) {
    double db = snk_to_f64(b);
    if (db == 0.0) return snk_val_float(0.0);
    return snk_val_float(snk_to_f64(a) / db);
}

static inline SnkValue snk_mod(SnkValue a, SnkValue b) {
    int64_t ib = snk_to_i64(b);
    if (ib == 0) return snk_val_int(0);
    return snk_val_int(snk_to_i64(a) % ib);
}

static inline SnkValue snk_neg(SnkValue a) {
    if (a.type == SNK_FLOAT) return snk_val_float(-a.as.f);
    return snk_val_int(-snk_to_i64(a));
}
static inline SnkValue snk_not(SnkValue a) { return snk_val_bool(!snk_to_bool(a)); }

/* Comparison Operations */
static inline SnkValue snk_eq(SnkValue a, SnkValue b) {
    if (a.type == SNK_STR && b.type == SNK_STR) return snk_val_bool(strcmp(a.as.s, b.as.s) == 0);
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) return snk_val_bool(snk_to_f64(a) == snk_to_f64(b));
    return snk_val_bool(snk_to_i64(a) == snk_to_i64(b));
}
static inline SnkValue snk_ne(SnkValue a, SnkValue b) { return snk_val_bool(!snk_to_bool(snk_eq(a, b))); }
static inline SnkValue snk_lt(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) return snk_val_bool(snk_to_f64(a) < snk_to_f64(b));
    return snk_val_bool(snk_to_i64(a) < snk_to_i64(b));
}
static inline SnkValue snk_gt(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) return snk_val_bool(snk_to_f64(a) > snk_to_f64(b));
    return snk_val_bool(snk_to_i64(a) > snk_to_i64(b));
}
static inline SnkValue snk_le(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) return snk_val_bool(snk_to_f64(a) <= snk_to_f64(b));
    return snk_val_bool(snk_to_i64(a) <= snk_to_i64(b));
}
static inline SnkValue snk_ge(SnkValue a, SnkValue b) {
    if (a.type == SNK_FLOAT || b.type == SNK_FLOAT) return snk_val_bool(snk_to_f64(a) >= snk_to_f64(b));
    return snk_val_bool(snk_to_i64(a) >= snk_to_i64(b));
}

/* List Operations */
static inline SnkList* snk_alloc_list(int64_t cap) {
    SnkList* l = (SnkList*)malloc(sizeof(SnkList));
    l->cap = cap > 8 ? cap : 8;
    l->len = 0;
    l->items = (SnkValue*)malloc(l->cap * sizeof(SnkValue));
    return l;
}

static inline SnkValue snk_list_create(SnkValue len_val, SnkValue def_val) {
    int64_t len = snk_to_i64(len_val);
    SnkList* l = snk_alloc_list(len + 8);
    l->len = len;
    for (int64_t i = 0; i < len; i++) {
        l->items[i] = def_val;
    }
    return snk_val_list(l);
}

static inline SnkValue snk_list_append(SnkValue lv, SnkValue v) {
    if (lv.type != SNK_LIST || !lv.as.list) return lv;
    SnkList* l = lv.as.list;
    if (l->len >= l->cap) {
        l->cap *= 2;
        l->items = (SnkValue*)realloc(l->items, l->cap * sizeof(SnkValue));
    }
    l->items[l->len++] = v;
    return lv;
}

static inline SnkValue snk_list_get(SnkValue lv, SnkValue idx_val) {
    if (lv.type != SNK_LIST || !lv.as.list) return snk_val_unit();
    int64_t idx = snk_to_i64(idx_val);
    SnkList* l = lv.as.list;
    if (idx < 0 || idx >= l->len) return snk_val_unit();
    return l->items[idx];
}

static inline SnkValue snk_list_set(SnkValue lv, SnkValue idx_val, SnkValue v) {
    if (lv.type != SNK_LIST || !lv.as.list) return snk_val_unit();
    int64_t idx = snk_to_i64(idx_val);
    SnkList* l = lv.as.list;
    if (idx >= 0 && idx < l->len) {
        l->items[idx] = v;
    }
    return snk_val_unit();
}

static inline SnkValue snk_size(SnkValue v) {
    if (v.type == SNK_LIST && v.as.list) return snk_val_int(v.as.list->len);
    if (v.type == SNK_STR && v.as.s) return snk_val_int(strlen(v.as.s));
    return snk_val_int(0);
}

/* UTF-8 Utilities */
static inline int utf8_char_len(unsigned char c) {
    if ((c & 0x80) == 0) return 1;
    if ((c & 0xE0) == 0xC0) return 2;
    if ((c & 0xF0) == 0xE0) return 3;
    if ((c & 0xF8) == 0xF0) return 4;
    return 1;
}

static inline FILE* utf8_fopen(const char* filename, const char* mode) {
#ifdef _WIN32
    wchar_t wfn[1024];
    wchar_t wmode[16];
    MultiByteToWideChar(CP_UTF8, 0, filename, -1, wfn, 1024);
    MultiByteToWideChar(CP_UTF8, 0, mode, -1, wmode, 16);
    return _wfopen(wfn, wmode);
#else
    return fopen(filename, mode);
#endif
}

static inline SnkValue snk_str_len(SnkValue sv) {
    if (sv.type != SNK_STR || !sv.as.s) return snk_val_int(0);
    const char* s = sv.as.s;
    int64_t count = 0;
    while (*s) {
        int l = utf8_char_len((unsigned char)*s);
        s += l;
        count++;
    }
    return snk_val_int(count);
}

static inline SnkValue snk_str_char_at(SnkValue sv, SnkValue idx_val) {
    if (sv.type != SNK_STR || !sv.as.s) return snk_val_str("");
    int64_t idx = snk_to_i64(idx_val);
    const char* s = sv.as.s;
    int64_t cur = 0;
    while (*s) {
        int l = utf8_char_len((unsigned char)*s);
        if (cur == idx) {
            char buf[8] = {0};
            memcpy(buf, s, l);
            buf[l] = '\0';
            return snk_val_str(buf);
        }
        s += l;
        cur++;
    }
    return snk_val_str("");
}

static inline SnkValue snk_str_slice(SnkValue sv, SnkValue s_val, SnkValue e_val) {
    if (sv.type != SNK_STR || !sv.as.s) return snk_val_str("");
    int64_t start = snk_to_i64(s_val);
    int64_t end = snk_to_i64(e_val);
    const char* s = sv.as.s;
    const char* p_start = NULL;
    const char* p_end = NULL;
    int64_t cur = 0;
    while (*s) {
        if (cur == start) p_start = s;
        if (cur == end) { p_end = s; break; }
        s += utf8_char_len((unsigned char)*s);
        cur++;
    }
    if (cur == start) p_start = s;
    if (!p_end) p_end = s;
    if (!p_start || p_start > p_end) return snk_val_str("");
    size_t len = p_end - p_start;
    char* buf = (char*)malloc(len + 1);
    memcpy(buf, p_start, len);
    buf[len] = '\0';
    SnkValue res; res.type = SNK_STR; res.type_tag = 0; res.as.s = buf; return res;
}

static inline SnkValue snk_str_split(SnkValue sv, SnkValue dv) {
    if (sv.type != SNK_STR || !sv.as.s) return snk_list_create(snk_val_int(0), snk_val_unit());
    const char* s = sv.as.s;
    const char* delim = (dv.type == SNK_STR && dv.as.s) ? dv.as.s : "";
    SnkList* l = snk_alloc_list(16);

    if (strlen(delim) == 0) {
        while (*s) {
            int cl = utf8_char_len((unsigned char)*s);
            char ch[8] = {0};
            memcpy(ch, s, cl);
            snk_list_append(snk_val_list(l), snk_val_str(ch));
            s += cl;
        }
        return snk_val_list(l);
    }

    size_t dlen = strlen(delim);
    const char* cur = s;
    while (1) {
        const char* next = strstr(cur, delim);
        if (!next) {
            snk_list_append(snk_val_list(l), snk_val_str(cur));
            break;
        }
        size_t part_len = next - cur;
        char* part = (char*)malloc(part_len + 1);
        memcpy(part, cur, part_len);
        part[part_len] = '\0';
        SnkValue v; v.type = SNK_STR; v.type_tag = 0; v.as.s = part;
        snk_list_append(snk_val_list(l), v);
        cur = next + dlen;
    }
    return snk_val_list(l);
}

static inline SnkValue snk_list_join(SnkValue lv, SnkValue dv) {
    if (lv.type != SNK_LIST || !lv.as.list) return snk_val_str("");
    SnkList* l = lv.as.list;
    const char* delim = (dv.type == SNK_STR && dv.as.s) ? dv.as.s : "";
    size_t total = 0;
    size_t dlen = strlen(delim);
    for (int64_t i = 0; i < l->len; i++) {
        if (i > 0) total += dlen;
        if (l->items[i].type == SNK_STR && l->items[i].as.s) {
            total += strlen(l->items[i].as.s);
        } else {
            total += 32;
        }
    }
    char* buf = (char*)malloc(total + 1);
    buf[0] = '\0';
    for (int64_t i = 0; i < l->len; i++) {
        if (i > 0) strcat(buf, delim);
        if (l->items[i].type == SNK_STR && l->items[i].as.s) {
            strcat(buf, l->items[i].as.s);
        } else if (l->items[i].type == SNK_FLOAT) {
            char fbuf[32]; sprintf(fbuf, "%.6f", l->items[i].as.f);
            strcat(buf, fbuf);
        } else if (l->items[i].type == SNK_INT) {
            char ibuf[32]; sprintf(ibuf, "%lld", (long long)l->items[i].as.i);
            strcat(buf, ibuf);
        }
    }
    SnkValue res; res.type = SNK_STR; res.type_tag = 0; res.as.s = buf; return res;
}

static inline SnkValue snk_str_to_num(SnkValue sv) {
    if (sv.type != SNK_STR || !sv.as.s) return snk_val_float(0.0);
    const char* s = sv.as.s;
    char ascii_buf[128];
    int p = 0;
    while (*s && p < 120) {
        if ((unsigned char)s[0] == 0xE0 && (unsigned char)s[1] == 0xA5 && ((unsigned char)s[2] >= 0xA6 && (unsigned char)s[2] <= 0xAF)) {
            ascii_buf[p++] = '0' + ((unsigned char)s[2] - 0xA6);
            s += 3;
        } else {
            ascii_buf[p++] = *s++;
        }
    }
    ascii_buf[p] = '\0';
    return snk_val_float(atof(ascii_buf));
}

static inline SnkValue snk_to_str(SnkValue v) {
    char buf[128];
    if (v.type == SNK_STR) return v;
    if (v.type == SNK_INT) sprintf(buf, "%lld", (long long)v.as.i);
    else if (v.type == SNK_FLOAT) sprintf(buf, "%.4f", v.as.f);
    else if (v.type == SNK_BOOL) sprintf(buf, "%s", v.as.b ? "सत्यम्" : "मिथ्या");
    else buf[0] = '\0';
    return snk_val_str(buf);
}

/* File I/O */
static inline SnkValue snk_file_read(SnkValue pv) {
    if (pv.type != SNK_STR || !pv.as.s) return snk_val_str("");
    FILE* f = utf8_fopen(pv.as.s, "rb");
    if (!f) return snk_val_str("");
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(sz + 1);
    fread(buf, 1, sz, f);
    buf[sz] = '\0';
    fclose(f);
    char* clean = (char*)malloc(sz + 1);
    int j = 0;
    for (int i = 0; i < sz; i++) {
        if (buf[i] != '\r') clean[j++] = buf[i];
    }
    clean[j] = '\0';
    free(buf);
    SnkValue res; res.type = SNK_STR; res.type_tag = 0; res.as.s = clean; return res;
}

static inline SnkValue snk_file_write(SnkValue pv, SnkValue cv) {
    if (pv.type != SNK_STR || !pv.as.s) return snk_val_unit();
    const char* content = (cv.type == SNK_STR && cv.as.s) ? cv.as.s : "";
    FILE* f = utf8_fopen(pv.as.s, "wb");
    if (f) {
        fputs(content, f);
        fclose(f);
    }
    return snk_val_unit();
}

static inline SnkValue snk_file_exists(SnkValue pv) {
    if (pv.type != SNK_STR || !pv.as.s) return snk_val_bool(false);
    FILE* f = utf8_fopen(pv.as.s, "rb");
    if (f) { fclose(f); return snk_val_bool(true); }
    return snk_val_bool(false);
}

/* Printing with Devanagari numeral transliteration */
static inline void snk_print_val(SnkValue v) {
    if (v.type == SNK_STR && v.as.s) {
        fputs(v.as.s, stdout);
    } else if (v.type == SNK_INT) {
        char buf[64]; sprintf(buf, "%lld", (long long)v.as.i);
        for (int i = 0; buf[i]; i++) {
            if (buf[i] >= '0' && buf[i] <= '9') {
                char dev[4] = {(char)0xE0, (char)0xA5, (char)(0xA6 + (buf[i] - '0')), 0};
                fputs(dev, stdout);
            } else fputc(buf[i], stdout);
        }
    } else if (v.type == SNK_FLOAT) {
        char buf[64]; sprintf(buf, "%.4f", v.as.f);
        for (int i = 0; buf[i]; i++) {
            if (buf[i] >= '0' && buf[i] <= '9') {
                char dev[4] = {(char)0xE0, (char)0xA5, (char)(0xA6 + (buf[i] - '0')), 0};
                fputs(dev, stdout);
            } else fputc(buf[i], stdout);
        }
    } else if (v.type == SNK_BOOL) {
        fputs(v.as.b ? "सत्यम्" : "मिथ्या", stdout);
    }
}

static inline SnkValue snk_print(int count, ...) {
    va_list args;
    va_start(args, count);
    for (int i = 0; i < count; i++) {
        SnkValue v = va_arg(args, SnkValue);
        snk_print_val(v);
    }
    va_end(args);
    printf("\n");
    return snk_val_unit();
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use sankode_lexer::Lexer;
    use sankode_parser::Parser;

    #[test]
    fn test_mangle_ident() {
        assert_eq!(mangle_ident("abc"), "_snk_abc");
        assert_eq!(mangle_ident("वर्णनाः"), "_snk_x0935x0930x094dx0923x0928x093ex0903");
    }

    #[test]
    fn test_generate_c_hello_world() {
        let src = "क्रिया मुख्य() -> रिक्त\nमुद्रय(\"नमस्ते जगत्!\")।\nइति";
        let tokens = Lexer::new(src).tokenize().unwrap();
        let prog = Parser::new(tokens).parse_program().unwrap();
        let c_code = generate_c_source(&prog).unwrap();
        assert!(c_code.contains("snk_main_entry"));
        assert!(c_code.contains("snk_print"));
        assert!(c_code.contains("नमस्ते जगत्!"));
    }

    #[test]
    fn test_generate_c_math_and_relu() {
        let src = "क्रिया मुख्य() -> रिक्त\nमान x = रेलू(-५.०)।\nमान y = महत्तम(१०, २०)।\nमान z = न्यूनतम(१०, २०)।\nइति";
        let tokens = Lexer::new(src).tokenize().unwrap();
        let prog = Parser::new(tokens).parse_program().unwrap();
        let c_code = generate_c_source(&prog).unwrap();
        assert!(c_code.contains("snk_relu"));
        assert!(c_code.contains("snk_max"));
        assert!(c_code.contains("snk_min"));
    }
}
